// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdeOC7ZzP-TpUwZzTodJx-GvnHUus6hQ',
    appId: '1:172724109548:web:f0758dfdb0a11a6f99a5c9',
    messagingSenderId: '172724109548',
    projectId: 'reddit-clone-5f80c',
    authDomain: 'reddit-clone-5f80c.firebaseapp.com',
    storageBucket: 'reddit-clone-5f80c.appspot.com',
    measurementId: 'G-5PKPPQW2JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgccuEfxxjLcFIzaYNwcAheEp8JVO8Tls',
    appId: '1:172724109548:android:61232d2ed061591199a5c9',
    messagingSenderId: '172724109548',
    projectId: 'reddit-clone-5f80c',
    storageBucket: 'reddit-clone-5f80c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkAsotp4Ag0t1q1z9lLSsPLFMy0v37C08',
    appId: '1:172724109548:ios:de62a2b8b426248e99a5c9',
    messagingSenderId: '172724109548',
    projectId: 'reddit-clone-5f80c',
    storageBucket: 'reddit-clone-5f80c.appspot.com',
    androidClientId: '172724109548-jkv42kb912t3judok0npm89k2003ceo1.apps.googleusercontent.com',
    iosClientId: '172724109548-rlqdhnpft7fdhd0ou6p3og7tta57hau5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkAsotp4Ag0t1q1z9lLSsPLFMy0v37C08',
    appId: '1:172724109548:ios:6a5d695f411de89e99a5c9',
    messagingSenderId: '172724109548',
    projectId: 'reddit-clone-5f80c',
    storageBucket: 'reddit-clone-5f80c.appspot.com',
    androidClientId: '172724109548-jkv42kb912t3judok0npm89k2003ceo1.apps.googleusercontent.com',
    iosClientId: '172724109548-cneqq3p7sn83v7qj46gl4b9tblsuc6mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone.RunnerTests',
  );
}
